### ISSUE TITLE
Dataset download error

### ISSUE THREAD

**Issue by puruBHU** [CancerDataScience/CrowdsourcingDataset-Amgadetal2019#13]
I am unable to download the dataset. 

Getting following error when running
`python download_crowdsource_dataset.py`

```
> raise SSLError(e, request=request)
> requests.exceptions.SSLError: HTTPSConnectionPool(host='demo.kitware.com', port=443): Max retries exceeded with url: /histomicstk/api/v1/api_key/token?key=n0Kp1ez8YOnOiWNoACryzeBlIzbUDW3iOD2DmPLI (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
```

I using miniconda with python 3.8

**Comment by puruBHU** [comment]
The issue resolved.
The problem was due to my network firewall which was blocking the connection.

**Comment by kheffah** [comment]
@puruBHU Thank you for letting us know what caused the issue. This helps others who may face the same problem.
