### ISSUE TITLE
Question regarding roiBounds.csv

### ISSUE THREAD

**Issue by Reasat** [CancerDataScience/CrowdsourcingDataset-Amgadetal2019#4]
Hi 
I have a question regarding ROI dimension.
In the [roiBounds.csv](https://github.com/CancerDataScience/CrowdsourcingDataset-Amgadetal2019/blob/master/meta/roiBounds.csv), the ROI dimension should be calculated by (x_max-x_min, y_max-y_min) (according to my understanding). But I get a different value when inferring the size from rgb images.

For example, for the file TCGA-A1-A0SK-DX1_xmin45749_ymin25055_MPP-0.2300.png the image size is 5092 x 3700
```
 import magic 
 magic.from_file('images/TCGA-A1-A0SK-DX1_xmin45749_ymin25055_MPP-0.2300.png')
'PNG image data, 5092 x 3700, 8-bit/color RGB, non-interlaced'`
```
while from the roiBounds.csv data

(49789 - 45749, 27991 - 25055) = (4040, 2936)

Why are they different?

**Comment by kheffah** [comment]
Hi @Reasat,
Thanks for your question. Actually, this is because the coordinates in the roiBounds.csv file as well as the image name as all at scan magnification. But the actual RGB dimensions are at whichever magnification you specify at `configs.py`. At a 0.23 MPP resolution, the magnification is roughly ~40x, but that particular slide was scanned at a smaller resolution. 
So there's nothing to worry about :)

**Comment by Reasat** [comment]
Thanks for the answer! I ran the download code with both MPP and MAG set to None. According to the instructions it will extract the ROI at base magnitude. The downloaded image dimensions now match with the numbers reported in roiBounds.csv.

I have a slight confusion. If I load the wsi image (in this case,  TCGA-A1-A0SK-DX1) and print the metadata, I see the magnification is reported as 40. Is this the base magnification? But if that's true, then why was there a mismatch in the ROIs when it was extracted at 0.23 MPP? In other words, what is the value of the lower base magnification?

```
path = '../wsis/TCGA-A1-A0SK-01Z-00-DX1.A44D70FA-4D96-43F4-9DD7-A61535786297.svs'
ts = large_image.getTileSource(path)
ts.getMetadata()

{'levels': 10,
 'sizeX': 125753,
 'sizeY': 75078,
 'tileWidth': 256,
 'tileHeight': 256,
 'magnification': 40.0,
 'mm_x': 0.0002521,
 'mm_y': 0.0002521}
 ```
 
 Thanks again!

**Comment by kheffah** [comment]
@Reasat Also, why 

> Note that when I redownloaded the files, I only downloaded the rgb and annotation at base magnitude. Do I also have to redownload the wsi images to get the actual base magnification?

@Reasat Also, why are you downloading the annotation jsons instead of the mask? If you want everything at scan magnification, simply set BOTH `MPP=None` and `MAG=None`.

**Comment by Reasat** [comment]
Thanks for the info regarding MPP! Sorry I meant to say rgb and *mask in the previous comment.
