### ISSUE TITLE
OSError: image file is truncated (20 bytes not processed)

### ISSUE THREAD

**Issue by YongQuanYang** [CancerDataScience/CrowdsourcingDataset-Amgadetal2019#5]
Hello, thanks for sharing your dataset. It's a very nice work. 

When downloading the dataset, I got an error like "OSError: image file is truncated (20 bytes not processed)". It seems that the rgb image is oversized for the Image object. How can I sovel this problem.

Thank you.

**Comment by hongjianyuan** [comment]
I also have this kind of problem, have you solved it？
thanks

**Comment by YongQuanYang** [comment]
> I also have this kind of problem, have you solved it？
> thanks
I skipped this error by following codes:

                resp = cf.gc.get(getStr, jsonResp=False)
                image_content = BytesIO(resp.content)
                image_content = image_content.getvalue()
                img = cv2.imdecode(np.frombuffer(image_content, np.uint8), cv2.IMREAD_COLOR)
                rgb_img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)
                save_path = os.path.join(
                    cf.savepaths['images'], "%s_xmin%d_ymin%d_%s.png"
                    % (row[''], xmin, ymin, append_str))
                cv2.imwrite(save_path, rgb_img)

But, I got some images that seems to be incomplete.
![image](https://user-images.githubusercontent.com/27262385/111092222-69a22f00-8570-11eb-8465-70a3739a0705.png)

**Comment by YongQuanYang** [comment]
I got this error in the environment of Python 3.5, and it dispeared when I changed to Python 3.6.

**Comment by hongjianyuan** [comment]
I'm glad to see you solve the problem, but I don't think this is a python version problem, because I am using python3.6 now

**Comment by hongjianyuan** [comment]
> 我在Python 3.5的环境中遇到此错误，当我更改为Python 3.6时，该错误消失了。

I'm glad to see you solve the problem, but I don't think this is a python version problem, because I am using python3.6 now

**Comment by hongjianyuan** [comment]
> I got this error in the environment of Python 3.5, and it dispeared when I changed to Python 3.6.

I'm glad to see you solve the problem, but I don't think this is a python version problem, because I am using python3.6 now

**Comment by AjeyPaiK** [comment]
Hi, thank you very much for making the data public. It is brilliant work!

I am using Python 3.8.10. I tried downloading the dataset as described in the repo. But for some reason, I am getting a similar error. Can you please reopen this issue and suggest the right solution?
![error](https://user-images.githubusercontent.com/26798611/132821507-458d1159-d328-4686-b0f3-c9e0212aed91.png)

**Comment by AjeyPaiK** [comment]
Hi, thank you very much for making the data public. It is brilliant work!

I am using Python 3.8.10. I tried downloading the dataset as described in the repo. But for some reason, I am getting a similar error. Can you please reopen this issue and suggest the right solution?
![error](https://user-images.githubusercontent.com/26798611/132821758-af8397ad-c956-4fcf-bcb2-45f3511b74d9.png)
