### ISSUE TITLE
link not accessible

### ISSUE THREAD

**Issue by kspham** [CancerDataScience/CrowdsourcingDataset-Amgadetal2019#7]
Amgad M, Elfandy H, ..., Gutman DA, Cooper LAD. Structured crowdsourcing enables convolutional segmentation of histology images. Bioinformatics. 2019. doi: 10.1093/bioinformatics/btz083

This data can be visualized in a public instance of the DSA at https://goo.gl/cNM4EL.

Seems that link is not available..

**Comment by kheffah** [comment]
Thank you for pointing this out. The server needed to be rebooted for some reason. Now everything is back online.
Cheers,
