### ISSUE TITLE
File not found in folder ./wsis

### ISSUE THREAD

**Issue by sorobedio** [CancerDataScience/CrowdsourcingDataset-Amgadetal2019#8]
Hello. after downloading the dataset with the first command . i could not  find the file `download_wsis.sh

**Comment by sorobedio** [comment]
ok i see . you comment what should be download in the code. but i still don't understand the need of this missing file

**Comment by SagaraBattousai** [comment]
I also have the same issue on windows, when running the script (from the repo directory as the script's paths are relative to the repo). I get the same message for each of the 151 lines, e.g: 
girder-client --api-url https://demo.kitware.com/histomicstk/api/v1/ --api-key n0Kp1ez8YOnOiWNoACryzeBlIzbUDW3iOD2DmPLI download 5bbdeed8e629140048d01bd7 ../Dataset\wsis
Fatal error in launcher: Unable to create process using '"<PathToBaseDir>\venv\scripts\python.exe"  "<PathToBaseDir>\venv\Scripts\girder-client.exe" --api-url https://demo.kitware.com/histomicstk/api/v1/ --api-key n0Kp1ez8YOnOiWNoACryzeBlIzbUDW3iOD2DmPLI download 5bbdeed8e629140048d01bd7 ../Dataset\wsis': The system cannot find the file specified.

**Comment by SagaraBattousai** [comment]
It seemed to be an issue with virtualenv, once I pip installed "girder-client" to my user pip (not just my venv) and ran the bat script it downloaded as expected.

**Comment by kheffah** [comment]
@SagaraBattousai Thank you for identifying the source of the issue.
@sorobedio I hope this solve the problem for you. Also, I would like to note that you don't _need_ the WSIs themselves to train the models. You only need the mask and RGB. Downloading the WSIs is only relevant if you'd like to do inference on a whole-slide level after you've already trained your model. The Kitware server is not necessarily equipped for so many requests to download the huge WSI slides .. if you'd like to download all WSIs you can alternatively use the Broad Institute website, as outlined in [this tutotial](http://www.andrewjanowczyk.com/download-tcga-digital-pathology-images-ffpe/).
